In [1]:
import numpy as np

array = np.random.randint(0, 100, size=(12, 5))

print("Original Array:")
print(array)

new_last_row = np.array([1, 2, 3, 4, 5])

array[-1] = new_last_row


print("\nArray after updating the last row:")
print(array)


Original Array:
[[89  0 72 38 25]
 [67 76 23 19 66]
 [16  3 40 37  2]
 [69 84 20 66  5]
 [42 46 48 81 70]
 [ 8 18 18 28 22]
 [13 88  3 37  1]
 [36  3 59 43 44]
 [27 88 39 22 38]
 [68 63 53 19 69]
 [89 72 56 80 68]
 [57 45 15 34  0]]

Array after updating the last row:
[[89  0 72 38 25]
 [67 76 23 19 66]
 [16  3 40 37  2]
 [69 84 20 66  5]
 [42 46 48 81 70]
 [ 8 18 18 28 22]
 [13 88  3 37  1]
 [36  3 59 43 44]
 [27 88 39 22 38]
 [68 63 53 19 69]
 [89 72 56 80 68]
 [ 1  2  3  4  5]]


In [2]:
import numpy as np

def min_max_per_row(array):

    min_per_row = np.min(array, axis=1)
    max_per_row = np.max(array, axis=1)

    min_max_array = np.column_stack((min_per_row, max_per_row))

    return min_max_array

array = np.random.randint(0, 100, size=(12, 5))

print("Original Array:")
print(array)

min_max_values = min_max_per_row(array)

print("\nMinimum and Maximum values per row:")
print(min_max_values)


Original Array:
[[45 57 30 48 51]
 [40 42 85 35 57]
 [32  6 59 62  7]
 [33  4 20 17 16]
 [61 27 74 23 42]
 [35 56 35 84 23]
 [15 28 25  3 82]
 [41 22 45 18 12]
 [49 82 66 66 11]
 [ 6 80 29 91 77]
 [81 43 71 97  7]
 [70 59 39 35  4]]

Minimum and Maximum values per row:
[[30 57]
 [35 85]
 [ 6 62]
 [ 4 33]
 [23 74]
 [23 84]
 [ 3 82]
 [12 45]
 [11 82]
 [ 6 91]
 [ 7 97]
 [ 4 70]]
